package main

// Code generated by ../../scripts/python/genpluginimport.py ../../config.yml -o plugin_config.go; 2021-10-25 04:12:42.985548; DO NOT EDIT.

import (
	_ "hiddenbridge/pkg/plugins/fakehostcom"
	_ "hiddenbridge/pkg/plugins/fakeredirecthostcom"
	_ "hiddenbridge/pkg/plugins/gitcache"
	_ "hiddenbridge/pkg/plugins/githubcom"
	_ "hiddenbridge/pkg/plugins/goproxy"
	_ "hiddenbridge/pkg/plugins/hiddenbridgeorg"
)
