global:
  # listen.ip: "192.168.226.135"
  listen.dev: "ens33"
  ca.cert: &cacert "keys/hiddenbridgeCA.pem"
  ca.key: "keys/hiddenbridgeCA.key"
  host.default: "hiddenbridge.org"

plugins:
  gitcache:
    hosts:
      - &cachehost gitcache.org
    ports.https:
      - 443
    ports.http:
      - 80
    cache.path: "/tmp/gitcache/cache"
    forward.proxy: "http://192.168.226.134:8888"
  hiddenbridgeorg:
    hosts:
      - hiddenbridge.org
    ports.https:
      - 443
    ports.http:
      - 80
    ca.cert: *cacert

  githubcom:
    hosts:
      - github.com
    ports.https:
      - 443
    ports.http:
      - 80
    upstream.host: "http://192.168.226.139/github"
    cache.host: *cachehost
    # host.real.http: "http://github.com:80"
    # host.real.proxy: "http://192.168.226.134:8888"

  goproxy:
    hosts:
      - proxy.golang.org
    site.keys:
      - "keys/goproxy.key"
    site.certs:
      - "keys/goproxy.pem"
    ports.https:
      - 443
    ports.http:
      - 80

  fakehostcom:
    hosts:
      - fakehost.com
      - "192.168.226.134"
    ports.https:
      - 443
      - 8443
    ports.http:
      - 80
      - 8080
    host.real.https: "https://192.168.226.134:8443"
    host.real.http: "http://192.168.226.134:8080"
    host.real.proxy: "http://192.168.226.134:8888"

  fakeredirecthostcom:
    hosts:
      - fakeredirecthost.com
    ports.https:
      - 443
    ports.http:
      - 80
    host.redirect.https: "https://fakehost.com:443"
    host.redirect.http: "http://fakehost.com:80"
