proxy_plugins:
    githubcom:
      hosts: 
        - fakegithub.com
      ports.secure:
        - 9000
      ports.insecure:
        - 9001
    fakehostcom:
      hosts:
        - fakehost.com
        - "192.168.226.134"
      ports.secure:
        - 9000
        - 8443
      ports.insecure:        
        - 9001
        - 8080
      host.real.secure: "https://192.168.226.134:8443"
      host.real.insecure: "http://192.168.226.134:8080"
      host.real.proxy: "http://192.168.226.134:8888"
    fakeredirecthostcom:
      hosts:
        - fakeredirecthost.com
      ports.secure:
        - 9000
      ports.insecure:        
        - 9001
      host.redirect.secure: "https://fakehost.com:9000"
      host.redirect.insecure: "http://fakehost.com:9001"
proxy_server:
    # listen.ip: "192.168.226.135"
    listen.dev: "ens33"
    ca.cert: "keys/hiddenbridgeCA.pem"
    ca.key: "keys/hiddenbridgeCA.key"
