global:
  # listen.ip: "192.168.226.135"
  listen.dev: "ens33"
  ca.cert: "keys/hiddenbridgeCA.pem"
  ca.key: "keys/hiddenbridgeCA.key"

plugins:
  githubcom:
    hosts:
      - github.com
    ports.https:
      - 9000
    ports.http:
      - 9001
    host.real.https: "https://github.com:443"
    host.real.http: "http://github.com:80"
    host.real.proxy: "http://192.168.226.134:8888"

  goproxy:
    hosts:
      - proxy.golang.org
    site.keys:
      - "keys/goproxy.key"
    site.certs:
      - "keys/goproxy.pem"
    ports.https:
      - 9000
    ports.http:
      - 9001

  fakehostcom:
    hosts:
      - fakehost.com
      - "192.168.226.134"
    ports.https:
      - 9000
      - 8443
    ports.http:
      - 9001
      - 8080
    host.real.https: "https://192.168.226.134:8443"
    host.real.http: "http://192.168.226.134:8080"
    host.real.proxy: "http://192.168.226.134:8888"

  fakeredirecthostcom:
    hosts:
      - fakeredirecthost.com
    ports.https:
      - 9000
    ports.http:
      - 9001
    host.redirect.https: "https://fakehost.com:9000"
    host.redirect.http: "http://fakehost.com:9001"
