package main

// Code generated by ./python/genpluginimport.py ./config.yml -o ./plugin_config.go; DO NOT EDIT.
//go:generate ./python/genpluginimport.py ./config.yml -o ./plugin_config.go

import (
	_ "hiddenbridge/plugins/fakehostcom"
	_ "hiddenbridge/plugins/fakeredirecthostcom"
	_ "hiddenbridge/plugins/githubcom"
	_ "hiddenbridge/plugins/goproxy"
)
